name: Collect Economic Data

on:
  schedule:
    - cron: '0 18 * * *'  # 한국 시간 새벽 3시
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run fetch script
        env:
          ECOS_API_KEY: ${{ secrets.ECOS_API_KEY }}
          FRED_API_KEY: ${{ secrets.FRED_API_KEY }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: python run_collector.py
